version: '3.8'

services:
  frontend:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    environment:
      - REACT_APP_BACKEND_URL=http://spring-app:8081
    networks:
      - crud-application_default

networks:
  crud-application_default:
    external: true
